# Generated by Django 3.2.5 on 2022-01-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=100)),
                ('subject', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='immo_bien',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_lot', models.TextField(null=True)),
                ('nb_piece', models.IntegerField(null=True)),
                ('typologie', models.CharField(max_length=200, null=True)),
                ('prix_tva_reduite', models.CharField(max_length=200, null=True)),
                ('prix_tva_normale', models.FloatField(null=True)),
                ('prix_ht', models.FloatField(null=True)),
                ('prix_m2_ht', models.FloatField(null=True)),
                ('prix_m2_ttc', models.FloatField(null=True)),
                ('orientation', models.CharField(max_length=200, null=True)),
                ('exterieur', models.CharField(max_length=200, null=True)),
                ('balcony', models.BooleanField(null=True)),
                ('garden', models.BooleanField(null=True)),
                ('parking', models.IntegerField(null=True)),
                ('ville', models.CharField(max_length=200, null=True)),
                ('departement', models.CharField(max_length=200, null=True)),
                ('date_fin_programme', models.CharField(max_length=200, null=True)),
                ('adresse_entiere', models.TextField(null=True)),
                ('date_extraction', models.CharField(max_length=200, null=True)),
                ('surface', models.FloatField(blank=True, null=True)),
                ('etage', models.CharField(max_length=20, null=True)),
                ('nom_programme', models.TextField(blank=True)),
                ('promoteur', models.TextField(blank=True)),
            ],
        ),
    ]
